### ISSUE TITLE
Any plans to support BigInts?

### ISSUE THREAD

**Issue by don1989** [izolate/millify#18]
Hi there!
I noticed we throw an error whenever we're out of the range of Number.MAX_SAFE_INTEGER and Number.MIN_SAFE_INTEGER. Are there any plans to support BigInt so we can exceed this range sometime in the future?
Cheers

**Comment by izolate** [comment]
Hi @don1989, No I haven't considered it and prefer to stay within the "safe" integer range because this project uses APIs that expect `Number` types. What's your use case for such large numbers?

**Comment by don1989** [comment]
Hi there, thanks for getting back to me. It's highly unlikely we'll be using such large numbers but I wanted to see the extent to which we can go. Thanks!
Closing.
