### ISSUE TITLE
Values rounded up to 1000K are not converted to 1M

### ISSUE THREAD

**Issue by rahulk94** [izolate/millify#25]
Values which are supposed to be rounded up to 1M are being shown as 1000K instead. This needs to be fixed otherwise its an edge case that consumers of this module need to work around. 

See screenshot below from RunJS (a JS sandbox).

![image](https://user-images.githubusercontent.com/4899473/117737105-38cb3700-b24d-11eb-971b-9dde7a81d1b5.png)

**Comment by izolate** [comment]
Verified. Thanks for reporting this @rahulk94, will get this fixed ASAP
