### ISSUE TITLE
[error] l got this error

### ISSUE THREAD

**Issue by yklydxtt** [izolate/millify#26]
![image](https://user-images.githubusercontent.com/52593709/121490420-8d5a0180-ca07-11eb-8b8b-c04678e8d98c.png)
the value is 109491601276928

**Comment by mooSylla** [comment]
I just tried that number  and it worked ,  think this issue needs to be closed.

**Comment by izolate** [comment]
Works for me too, so I'm closing this issue. Please update to the latest version if you can, and if the problem persists, feel free to re-open this issue @yklydxtt
