### ISSUE TITLE
`millify` does not check for `undefined` or `null` values

### ISSUE THREAD

**Issue by MatthewHerbst** [izolate/millify#28]
When first calling `millify` the package passes the value to `parseValue`. On the first line there it calls `value.toString()` without first checking if `value` actually exists:

https://github.com/izolate/millify/blob/8cc295de03374101feddcbe2a002834dbf609a58/lib/utils.ts#L4-L14

```ts
// Change this
const val: number = parseFloat(value.toString());

// To this
const val: number = parseFloat(value?.toString());
```

See [this StackOverflow post](https://stackoverflow.com/questions/73057515/typeerror-cannot-read-properties-of-undefined-reading-tostring-shows-in-con/73057804#73057804) for an example of how this can be problematic

**Comment by izolate** [comment]
Thank you for finding this bug and for the suggested fix @MatthewHerbst ! The fix has been published in release version [v4.0.1](https://github.com/izolate/millify/releases/tag/v4.0.1).

By the way, you said this package is not maintained in your StackOverflow link. That's untrue; I consider this package feature-complete and tend to prioritize bugfixes over feature requests. I'm not perfect, but I do the best I can with the time I have available.

**Comment by izolate** [comment]
[v5.0.0](https://github.com/izolate/millify/releases/tag/v5.0.0) has now been published with graceful fallback for invalid values. Didn't have frontend/UI in mind when I wrote this library, but I think it makes sense.

**Comment by MatthewHerbst** [comment]
Good to know, thanks!!
