### ISSUE TITLE
Unexpected token operator when doing a build using create-react-app

### ISSUE THREAD

**Issue by peterkuiper** [izolate/millify#4]
`npm run build` generates the following error:

```
static/js/main.31e960bf.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [./~/millify/index.js:7,0]
```

```
npm ls millify
...
└── millify@2.0.1
```

**Comment by peterkuiper** [comment]
Since your module is pure ES6, this does not work out of the box with create-react-app.

**Comment by weijiekoh** [comment]
Here's an alternative that works with `create-react-app`:
https://www.npmjs.com/package/unitize

**Comment by izolate** [comment]
@peterkuiper Closing this for now as I have verified the latest version works out of the box with CRA. Can you give it another shot? Feel free to re-open if it doesn't work for you, and please provide a codesandbox (or equivalent) link to reproduce.

**Comment by peterkuiper** [comment]
@izolate I'd really like to retry but I can't remember what project i used it in 😁 We might have used something else.

**Comment by izolate** [comment]
It was a long time ago, so I don't blame you for not remembering @peterkuiper. Anyway, thanks for reporting it.
